# == This file defines the page layouts for new pages.
#
# For further informations please see http://guides.alchemy-cms.com/create_page_layouts.html

- name: index
  unique: true
  cells: left_column
  elements: [article, image, text]
  autogenerate: [article]
- name: blog
  cells: [slider]
  elements: [blog_title, blog_post, categories_block, featured]
  autogenerate: [blog_title]
- name: contact
  unique: true
  cache: false
  elements: [pageheading, heading, contactform]
  autogenerate: [contactform]
